In [1]:
import netCDF4 as nc
import matplotlib.pyplot as plt
import numpy as np
import cartopy as cp
import os

In [2]:
import iris
import iris.quickplot as qplt
import iris.plot as iplt

In [3]:
path = 'W:\\2 Clients\\European Commission\\LUC4C\\Incoming Documents\\JRC_albedo_transitions_LUC\\Albedo.nc'

In [4]:
wf = nc.Dataset(path)

In [5]:
print wf

<type 'netCDF4._netCDF4.Dataset'>
root group (NETCDF3_CLASSIC data model, file format NETCDF3):
    dimensions(sizes): lon(360), lat(180), mon(12), iTr(28)
    variables(dimensions): float64 lon(lon), float64 lat(lat), int32 mon(mon), float64 iTr(iTr), float32 Delta_Albedo(iTr,mon,lat,lon), float32 SD_Delta_Albedo(iTr,mon,lat,lon)
    groups: 



In [6]:
iuse = iris.load(path)

C:\Users\Ivan\Anaconda2\lib\site-packages\iris\fileformats\cf.py:1139: UserWarning: NetCDF default loading behaviour currently does not expose variables which define reference surfaces for dimensionless vertical coordinates as independent Cubes. This behaviour is deprecated in favour of automatic promotion to Cubes. To switch to the new behaviour, set iris.FUTURE.netcdf_promote to True.
  warnings.warn(msg)


In [7]:
diff = iuse[1]
std = iuse[0]

In [8]:
wf['iTr'][:]

array([ 12.,  13.,  14.,  15.,  16.,  17.,  18.,  23.,  24.,  25.,  26.,
        27.,  28.,  34.,  35.,  36.,  37.,  38.,  45.,  46.,  47.,  48.,
        56.,  57.,  58.,  67.,  68.,  78.])

In [9]:
iTr_lookup = {12: 'Tree Broadleaf Evergreen to Tree Broadleaf Deciduous',
              13: 'Tree Broadleaf Evergreen to Tree Needleleaf Evergreen',
              14: 'Tree Broadleaf Evergreen to Tree Needleleaf Deciduous',
              15: 'Tree Broadleaf Evergreen to Shrubs',
              16: 'Tree Broadleaf Evergreen to Natural Grass',
              17: 'Tree Broadleaf Evergreen to Managed Grass',
              18: 'Tree Broadleaf Evergreen to Bare Soil',
              23: 'Tree Broadleaf Deciduous to Tree Needleleaf Evergreen',
              24: 'Tree Broadleaf Deciduous to Tree Needleleaf Decidous',
              25: 'Tree Broadleaf Deciduous to Shrubs',
              26: 'Tree Broadleaf Deciduous to Natural Grass',
              27: 'Tree Broadleaf Deciduous to Managed Grass',
              28: 'Tree Broadleaf Deciduous to Bare Soil',
              34: 'Tree Needleleaf Evergreen to Tree Needleleaf Deciduous',
              35: 'Tree Needleleaf Evergreen to Shrubs',
              36: 'Tree Needleleaf Evergreen to Natural Grass',
              37: 'Tree Needleleaf Evergreen to Managed Grass',
              38: 'Tree Needleleaf Evergreen to Bare Soil',
              45: 'Tree Needleleaf Deciduous to Shrubs',
              46: 'Tree Needleleaf Deciduous to Natural Grass',
              47: 'Tree Needleleaf Deciduous to Managed Grass',
              48: 'Tree Needleleaf Deciduous to Bare Soil',
              56: 'Shrubs to Natural Grass',
              57: 'Shrubs to Managed Grass',
              58: 'Shrubs to Bare Soil',
              67: 'Natural Grass to Managed Grass',
              68: 'Natural Grass to Bare Soil',
              78: 'Managed Grass to Bare Soil'    
                }

m_lookup = {1: 'Jan',
            2: 'Feb',
            3: 'Mar',
            4: 'Apr',
            5: 'May',
            6: 'Jun',
            7: 'Jul',
            8: 'Aug',
            9: 'Sep',
            10: 'Oct',
            11: 'Nov',
            12: 'Dec'}

In [14]:
for i in range(0,len(wf['iTr'])):

    ax = plt.axes(projection = cp.crs.PlateCarree())
    ax.stock_img()
    #qplt.pcolormesh(std[i,0,:,:])
    print np.max(std[i].data)
    #plt.title(iTr_lookup[wf['iTr'][i]])
    #plt.show()

0.243869
0.28986
0.0592089
0.428314
0.209177
0.264373
0.404986
0.942283
0.393733
0.774279
1.09301
0.46457
1.06483
0.456472
1.00173
0.907724
0.479059
0.561745
0.479186
0.77229
0.659086
0.382815
0.925779
0.90073
1.27687
0.802601
2.31455
0.680068


In [76]:
savedir = 'W:\\2 Clients\\European Commission\\LUC4C\\Implementation\\WP7\\LUC_albedo_cf'

mrange = [12,1,2,3,4,5,6,7,8,9,10,11]
for i, trkey in enumerate(iTr_lookup.keys()):  
    fig = plt.figure(figsize = (12,8), dpi=100)
    
    for j, month in enumerate(mrange):
        
        row = ((j%12)/3)+1
        col = j%3 +1  
        num = j+1
        ax = plt.subplot(4,3,num,projection = cp.crs.PlateCarree())
        #ax.coastlines(color = 'white')
        ax.stock_img()
        
        cmap = plt.cm.get_cmap('seismic',21)
        #cmap.set_bad('black')
        cf = iplt.pcolormesh(diff[i,j,:,:], vmin = -1, vmax = 1, cmap = cmap)
        #iplt.pcolormesh(diff[i,j,:,:], vmin = -1, vmax = 1, cmap = plt.cm.get_cmap('seismic', 21))
        
        plt.title(m_lookup[month], size=8)
        
    colorbar_axes = fig.add_axes([0.3, 0.07, 0.4, 0.02])
    colorbar = plt.colorbar(cf, colorbar_axes, orientation='horizontal')
    colorbar.set_label('Delta albedo', size=8)
    colorbar.ax.tick_params(labelsize=8)

    fig.suptitle(iTr_lookup[trkey])   
    fig.subplots_adjust(hspace=0.15, wspace=0.05, top=0.90, bottom=0.1, left=0.075, right=0.925)
    plt.savefig(os.path.join(savedir, '{}.png'.format(iTr_lookup[trkey])), transparent=True)
    plt.close()

In [22]:
#annual
savedir = 'W:\\2 Clients\\European Commission\\LUC4C\\Implementation\\WP7\\LUC_albedo_cf'

mrange = [12,1,2,3,4,5,6,7,8,9,10,11]
for i, trkey in enumerate(iTr_lookup.keys()):  
    fig = plt.figure(figsize = (12,8), dpi=100)
    ax = plt.axes(projection = cp.crs.PlateCarree())
    ax.coastlines(color = 'white')
    #ax.stock_img()
    cmap = plt.cm.get_cmap('seismic',21)
    cmap.set_bad('black')
    diff_ann = diff.collapsed('mon', iris.analysis.MEAN)
    cf = iplt.pcolormesh(diff_ann[i,:,:], vmin = -1, vmax = 1, cmap = cmap)
    #iplt.pcolormesh(diff[i,j,:,:], vmin = -1, vmax = 1, cmap = plt.cm.get_cmap('seismic', 21))

    colorbar_axes = fig.add_axes([0.3, 0.07, 0.4, 0.02])
    colorbar = plt.colorbar(cf, colorbar_axes, orientation='horizontal')
    colorbar.set_label('Delta albedo', size=8)
    colorbar.ax.tick_params(labelsize=8)

    fig.suptitle(iTr_lookup[trkey])   
    fig.subplots_adjust(hspace=0.15, wspace=0.05, top=0.90, bottom=0.1, left=0.075, right=0.925)
    plt.savefig(os.path.join(savedir, 'annual_BLACK_{}.png'.format(iTr_lookup[trkey])), transparent=True)
    plt.close()

C:\Users\Ivan\Anaconda2\lib\site-packages\matplotlib\artist.py:221: MatplotlibDeprecationWarning: This has been deprecated in mpl 1.5, please use the
axes property.  A removal date has not been set.
  warnings.warn(_get_axes_msg, mplDeprecation, stacklevel=1)


In [20]:
#by month single plot
#annual
savedir = 'W:\\2 Clients\\European Commission\\LUC4C\\Implementation\\WP7\\LUC_albedo_cf'

mrange = [12,1,2,3,4,5,6,7,8,9,10,11]
for i, trkey in enumerate(iTr_lookup.keys()):
    for j, month in enumerate(mrange):
        fig = plt.figure(figsize = (12,8), dpi=100)
        ax = plt.axes(projection = cp.crs.PlateCarree())
        #ax.coastlines(color = 'white')
        ax.stock_img()
        cmap = plt.cm.get_cmap('seismic',21)
        #cmap.set_bad('black')
        cf = iplt.pcolormesh(diff[i,j,:,:], vmin = -1, vmax = 1, cmap = cmap)
        #iplt.pcolormesh(diff[i,j,:,:], vmin = -1, vmax = 1, cmap = plt.cm.get_cmap('seismic', 21))

        colorbar_axes = fig.add_axes([0.3, 0.07, 0.4, 0.02])
        colorbar = plt.colorbar(cf, colorbar_axes, orientation='horizontal')
        colorbar.set_label('Delta albedo', size=8)
        colorbar.ax.tick_params(labelsize=8)

        fig.suptitle('{} {}'.format(m_lookup[month], iTr_lookup[trkey]))   
        fig.subplots_adjust(hspace=0.15, wspace=0.05, top=0.90, bottom=0.1, left=0.075, right=0.925)
        plt.savefig(os.path.join(savedir, '{}_month_{}.png'.format(iTr_lookup[trkey], month)), transparent=True)
        plt.close()

In [110]:
#both DeltaAlbedo and STDEV on same plot

savedir = 'W:\\2 Clients\\European Commission\\LUC4C\\Implementation\\WP7\\LUC_albedo_cf'

mrange = [12,1,2,3,4,5,6,7,8,9,10,11]
stdmax = np.nanpercentile(std.data,95)
for i, trkey in enumerate(iTr_lookup.keys()):
    for j, month in enumerate(mrange):
        fig = plt.figure(figsize = (12,4), dpi=100)
        
        cmap = plt.cm.get_cmap('seismic',21)
        cmap.set_bad('black')
        cmap_std = plt.cm.get_cmap('Greys_r',21)#cmap_std = plt.cm.get_cmap('Reds',21)
        cmap_std.set_bad('black')

        ax1 = plt.subplot(121, projection=cp.crs.PlateCarree())
        ax1.coastlines(color = 'grey')
        #ax1.stock_img()
        cf = iplt.pcolormesh(diff[i,j,:,:], vmin = -1, vmax = 1, cmap = cmap)
        
        #colorbar_axes = plt.gcf().add_axes([0.3, 0.07, 0.4, 0.02])
        colorbar = plt.colorbar(cf, ax=ax1, orientation='horizontal')
        colorbar.set_label('Delta albedo', size=8)
        colorbar.ax.tick_params(labelsize=8)

        ax2 = plt.subplot(122, projection=cp.crs.PlateCarree())
        ax2.coastlines(color = 'grey')
        #ax2.stock_img()
        cf_std = iplt.pcolormesh(std[i,j,:,:], cmap = cmap_std, vmin=0, vmax=stdmax)
                
        #colorbar_axes = plt.gcf().add_axes([0.3, 0.07, 0.4, 0.02])
        colorbar = plt.colorbar(cf_std, ax=ax2, orientation='horizontal', extend='max', format='%0.3f')
        colorbar.set_label('STD of Delta albedo', size=8)
        colorbar.ax.tick_params(labelsize=8)        

        fig.suptitle('{} {}'.format(m_lookup[month], iTr_lookup[trkey]))   
        fig.subplots_adjust(hspace=0, wspace=0.06, top=1, bottom=0., left=0.075, right=0.925)
        plt.savefig(os.path.join(savedir, 'wstd_BLACK_{}_month_{}.png'.format(iTr_lookup[trkey], month)), transparent=True)
        plt.close()

In [32]:
#both DeltaAlbedo and STDEV on same plot annual

savedir = 'W:\\2 Clients\\European Commission\\LUC4C\\Implementation\\WP7\\LUC_albedo_cf'

mrange = [12,1,2,3,4,5,6,7,8,9,10,11]
stdmax = np.nanpercentile(std.data,99)

diff_ann = diff.collapsed('mon', iris.analysis.MEAN)
std_ann = std.collapsed('mon', iris.analysis.MEAN)

for i, trkey in enumerate(iTr_lookup.keys()):
    
    fig = plt.figure(figsize = (24,8), dpi=100)

    cmap = plt.cm.get_cmap('seismic',21)
    cmap.set_bad('black')
    cmap_std = plt.cm.get_cmap('Greys_r',21)#cmap_std = plt.cm.get_cmap('Reds',21)
    cmap_std.set_bad('black')

    ax1 = plt.subplot(121, projection=cp.crs.PlateCarree())
    ax1.coastlines(color = 'grey')
    gl1 = ax1.gridlines(color='grey', draw_labels=True)
    gl1.xlabel_style = {'size': 8}
    gl1.ylabel_style = {'size': 8}
    gl1.xlabels_bottom = False
    gl1.ylabels_right = False
    #ax1.stock_img()
    cf = iplt.pcolormesh(diff_ann[i,:,:], vmin = -1, vmax = 1, cmap = cmap)

    #colorbar_axes = plt.gcf().add_axes([0.3, 0.07, 0.4, 0.02])
    colorbar = plt.colorbar(cf, ax=ax1, orientation='horizontal')
    colorbar.set_label('Delta albedo', size=8)
    colorbar.ax.tick_params(labelsize=8)

    ax2 = plt.subplot(122, projection=cp.crs.PlateCarree())
    ax2.coastlines(color = 'grey')
    gl2 = ax2.gridlines(color='grey', draw_labels=True)
    gl2.xlabel_style = {'size': 8}
    gl2.ylabel_style = {'size': 8}
    gl2.xlabels_top = False
    gl2.ylabels_left = False
    #ax2.stock_img()
    cf_std = iplt.pcolormesh(std_ann[i,:,:], cmap = cmap_std, vmin=0, vmax=stdmax)

    #colorbar_axes = plt.gcf().add_axes([0.3, 0.07, 0.4, 0.02])
    colorbar = plt.colorbar(cf_std, ax=ax2, orientation='horizontal', extend='max', format='%0.3f')
    colorbar.set_label('STD of Delta albedo', size=8)
    colorbar.ax.tick_params(labelsize=8)        

    fig.suptitle('{}'.format(iTr_lookup[trkey]))   
    fig.subplots_adjust(hspace=0, wspace=0.06, top=1, bottom=0., left=0.075, right=0.925)
    plt.savefig(os.path.join(savedir, 'wstd_BLACK_{}_annual.png'.format(iTr_lookup[trkey])), transparent=True)
    plt.close()

In [17]:
print np.nanmax(std_ann.data)
print np.nanpercentile(std_ann.data,[95,96,97,98,99,100])

0.439622203509
[ 0.00001011  0.00039133  0.00131141  0.00306293  0.00757092  0.4396222 ]


In [8]:
wf.variables['lat'][:]

array([ 89.5,  88.5,  87.5,  86.5,  85.5,  84.5,  83.5,  82.5,  81.5,
        80.5,  79.5,  78.5,  77.5,  76.5,  75.5,  74.5,  73.5,  72.5,
        71.5,  70.5,  69.5,  68.5,  67.5,  66.5,  65.5,  64.5,  63.5,
        62.5,  61.5,  60.5,  59.5,  58.5,  57.5,  56.5,  55.5,  54.5,
        53.5,  52.5,  51.5,  50.5,  49.5,  48.5,  47.5,  46.5,  45.5,
        44.5,  43.5,  42.5,  41.5,  40.5,  39.5,  38.5,  37.5,  36.5,
        35.5,  34.5,  33.5,  32.5,  31.5,  30.5,  29.5,  28.5,  27.5,
        26.5,  25.5,  24.5,  23.5,  22.5,  21.5,  20.5,  19.5,  18.5,
        17.5,  16.5,  15.5,  14.5,  13.5,  12.5,  11.5,  10.5,   9.5,
         8.5,   7.5,   6.5,   5.5,   4.5,   3.5,   2.5,   1.5,   0.5,
        -0.5,  -1.5,  -2.5,  -3.5,  -4.5,  -5.5,  -6.5,  -7.5,  -8.5,
        -9.5, -10.5, -11.5, -12.5, -13.5, -14.5, -15.5, -16.5, -17.5,
       -18.5, -19.5, -20.5, -21.5, -22.5, -23.5, -24.5, -25.5, -26.5,
       -27.5, -28.5, -29.5, -30.5, -31.5, -32.5, -33.5, -34.5, -35.5,
       -36.5, -37.5,

In [11]:
wf.variables['lon'][:]

array([-179.5, -178.5, -177.5, -176.5, -175.5, -174.5, -173.5, -172.5,
       -171.5, -170.5, -169.5, -168.5, -167.5, -166.5, -165.5, -164.5,
       -163.5, -162.5, -161.5, -160.5, -159.5, -158.5, -157.5, -156.5,
       -155.5, -154.5, -153.5, -152.5, -151.5, -150.5, -149.5, -148.5,
       -147.5, -146.5, -145.5, -144.5, -143.5, -142.5, -141.5, -140.5,
       -139.5, -138.5, -137.5, -136.5, -135.5, -134.5, -133.5, -132.5,
       -131.5, -130.5, -129.5, -128.5, -127.5, -126.5, -125.5, -124.5,
       -123.5, -122.5, -121.5, -120.5, -119.5, -118.5, -117.5, -116.5,
       -115.5, -114.5, -113.5, -112.5, -111.5, -110.5, -109.5, -108.5,
       -107.5, -106.5, -105.5, -104.5, -103.5, -102.5, -101.5, -100.5,
        -99.5,  -98.5,  -97.5,  -96.5,  -95.5,  -94.5,  -93.5,  -92.5,
        -91.5,  -90.5,  -89.5,  -88.5,  -87.5,  -86.5,  -85.5,  -84.5,
        -83.5,  -82.5,  -81.5,  -80.5,  -79.5,  -78.5,  -77.5,  -76.5,
        -75.5,  -74.5,  -73.5,  -72.5,  -71.5,  -70.5,  -69.5,  -68.5,
      